---
title: "savage_GLM"
output: html_document
---

```{r, SETTINGS-knitr, include=FALSE}
stopifnot(require(knitr))
options(width = 90)
opts_chunk$set(
  cache = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE
)
```

Load required packages:
```{r}
library(rethinking)
library(bayestestR)
library(brms)
options(mc.cores = parallel::detectCores())
library(tidyverse)
theme_set(theme_default())
library(readr)
library(tidyr)
library(Hmisc)
library(plyr)
library(RColorBrewer)
library(reshape2)
library(bayestestR)

library(gridExtra)


```


Load the data:
```{r}

setwd("/Users/lennart/Desktop/savage/MLM/") #change working dir

ds = read.csv("savage_long.csv")  # read from first sheet
n_sub <- 49
  
ds$group <- ifelse( ds$SubID < 900 , 1L , 2L )

ds[,'SubID']<-factor(ds[,'SubID'])
head(ds, 10)

conditions <- make_conditions(ds, "SubID")

#wide format

ds_wide = read.csv("savage_wide.csv")

#rsa data
ds_rsa = read.csv("rsa.csv")
ds_rsa_norm = read.csv("rsa_norm.csv")

#decoding data
ds_decoding = read.csv("decoding.csv")

ds_decoding1 = read.csv("decoding1.csv")
ds_decoding2 = read.csv("decoding2.csv")

#behavioral sample
ds_behav = ds[ which(ds$ofc_acc =='NaN'),]
ds_behav_wide = ds_wide[ 1:20,]
  
#fmri sample
ds_fmri = ds[ 81:196,]
ds_fmri_wide = ds_wide[ 21:49,]


#tbt data
ds_tbt = read.csv("savage_long_tbt.csv")  # read from first sheet
ds_tbt$group <- ifelse( ds_tbt$SubID < 900 , 1L , 2L )
head(ds_tbt, 10)




```


#Regression model on all CS choice probabilities, trial-by-trial
```{r}
# prior trimmed data list
dat_list <- list(
  choice = ds_tbt$choice,
  subject = ds_tbt$subject,
  CS = ds_tbt$CS,
  group = ds_tbt$group
)


#flat regression, no varying intercepts, no CS specific intercepts
reg_flat <- ulam(
  alist(
        choice ~ dbinom( 1 , p ) ,
        logit(p) <- a,
        a ~ dnorm( 0 , 1 )
  ) , data=dat_list , chains=4 , iter = 10000,cores = 4, log_lik=TRUE )  


precis( reg_flat, depth=2)
traceplot( reg_flat )
trankplot( reg_flat , n_cols= 3 )

#flat regression, no varying intercepts, but CS-specific effects
reg_flat_CS <- ulam(
  alist(
        choice ~ dbinom( 1 , p ) ,
        logit(p) <- a_bar + x[CS]*a_sigma,
        x[CS] ~ dnorm( 0 , 1 ),
        a_bar ~ dnorm( 0 , 1 ),
        a_sigma ~ dhalfnorm(  0 , .1 ),
        #generated quantities 
        gq> vector[CS]:a <<- a_bar + x*a_sigma
  ) , data=dat_list , chains=4 , iter = 10000, cores = 4, log_lik=TRUE )  

#parameter estimates
precis( reg_flat_CS , depth=2)
traceplot( reg_flat_CS )
trankplot( reg_flat_CS , n_cols= 3 )

#group model, no CS-specific effects
reg_group <- ulam(
  alist(
        choice ~ dbinom( 1 , p ) ,
        logit(p) <- a_bar + x[group]*a_sigma,
        x[group] ~ dnorm( 0 , 1 ),
        a_bar ~ dnorm( 0 , 1 ),
        a_sigma ~ dhalfnorm(  0 , .05 ),
        #generated quantities 
        gq> vector[group]:a <<- a_bar + x*a_sigma
  ) , data=dat_list , chains=4 , iter = 10000, cores = 4, log_lik=TRUE )  

#parameter estimates
precis( reg_group , depth=2)
traceplot( reg_group )
trankplot( reg_group , n_cols= 3 )

#group model, with CS-specific effects, correlated slopes
reg_group_CS_corr <- ulam(
  alist(
        choice ~ dbinom( 1 , p ) ,
        logit(p) <- d[CS] + g[group] + a[group,CS],
        # adaptive priors - non-centered
        transpars> matrix[group,4]:a <-
                   compose_noncentered( sigma , L_Rho , z ),
        matrix[4,group]:z ~ normal( 0 , 1 ),
        # fixed priors
        d[CS] ~ normal(0,1),
        g[group] ~ normal(0,1),
        vector[4]:sigma ~ dhalfnorm(  0 , .05 ),
        cholesky_factor_corr[4]:L_Rho ~ lkj_corr_cholesky( 2 ),
        #generated quantities 
        # compute ordinary correlation matrixes from Cholesky factors
        gq> matrix[4,4]:Rho <<- Chol_to_Corr(L_Rho)
  ) , data=dat_list , chains=4 , iter = 10000, cores = 4, log_lik=TRUE )


#parameter estimates
precis( reg_group_CS_corr , depth=3)
traceplot( reg_group_CS_corr )
trankplot( reg_group_CS_corr , n_cols= 3 )

#varying intercepts and CS effect regression correlated slopes
reg_var_int_CS_corr <- ulam(
  alist(
        choice ~ dbinom( 1 , p ) ,
        logit(p) <- d[CS] + a[subject,CS],
        # adaptive priors - non-centered
        transpars> matrix[subject,4]:a <-
                   compose_noncentered( sigma , L_Rho , z ),
        matrix[4,subject]:z ~ normal( 0 , 1 ),
        # fixed priors
        d[CS] ~ normal(0,1),
        vector[4]:sigma ~ dhalfnorm(  0 , .5 ),
        cholesky_factor_corr[4]:L_Rho ~ lkj_corr_cholesky( 4 ),
        #generated quantities 
        # compute ordinary correlation matrixes from Cholesky factors
        gq> matrix[4,4]:Rho <<- Chol_to_Corr(L_Rho)
  ) , data=dat_list , chains=4 , iter = 10000, cores = 4, log_lik=TRUE )


#parameter estimates
precis( reg_var_int_CS_corr , depth=3)
traceplot( reg_var_int_CS_corr )
trankplot( reg_var_int_CS_corr , n_cols= 3 )

#varying intercepts, group intercepts and CS effect regression, correlated slopes
reg_var_int_CS_group_corr <- ulam(
  alist(
        choice ~ dbinom( 1 , p ) ,
        logit(p) <- a_bar[CS] + a[subject,CS] + b_bar[group] + b[CS,group],
        # adaptive priors - non-centered
        transpars> matrix[subject,4]:a <-
                   compose_noncentered( sigma_a , L_Rho_a , z_a ),
        matrix[4,subject]:z_a ~ normal( 0 , 1 ),
        transpars> matrix[CS,2]:b <-
                   compose_noncentered( sigma_b , L_Rho_b , z_b ),
        matrix[2,CS]:z_b ~ normal( 0 , 1 ),
        # fixed priors
        a_bar[CS] ~ dnorm( 0 , 1 ),
        b_bar[group] ~ normal( 0 , 1 ),
        vector[4]:sigma_a ~ dhalfnorm(  0 , .1 ),
        vector[2]:sigma_b ~ dhalfnorm(  0 , .1 ),
        cholesky_factor_corr[4]:L_Rho_a ~ lkj_corr_cholesky( 2 ),
        cholesky_factor_corr[2]:L_Rho_b ~ lkj_corr_cholesky( 2 ),
        #generated quantities 
        # compute ordinary correlation matrixes from Cholesky factors
        gq> matrix[4,4]:Rho_a <<- Chol_to_Corr(L_Rho_a),
        gq> matrix[2,2]:Rho_b <<- Chol_to_Corr(L_Rho_b)
  ) , data=dat_list , chains=4 , iter = 10000 ,cores = 4, log_lik=TRUE )


#parameter estimates
precis( reg_var_int_CS_group_corr , depth=3)
traceplot( reg_var_int_CS_group_corr )
trankplot( reg_var_int_CS_group_corr , n_cols= 3 )

#model comparison
compare(reg_flat, reg_flat_CS, reg_group, reg_group_CS_corr, reg_var_int_CS_corr, reg_var_int_CS_group_corr, func = PSIS)



#extract posterior samples from best-fitting model
post_cs <- extract.samples( reg_var_int_CS_corr ) 

#CS1
M_a1 <- mean( inv_logit( post_cs$d[,1] ) ) #posterior mean on probability scale, behavioral sample
M_a1
HDI_a1 <- HPDI( inv_logit( post_cs$d[,1]  ) ) #highest posterior density on probability scale, behavioral sample
HDI_a1

#CS2
M_a2 <- mean( inv_logit( post_cs$d[,2] ) ) #posterior mean on probability scale, fmri sample
M_a2
HDI_a2 <- HPDI( inv_logit( post_cs$d[,2]  ) ) #highest posterior density on probability scale, fmri sample
HDI_a2

#CS1n
M_a3 <- mean( inv_logit( post_cs$d[,3] ) ) #posterior mean on probability scale, behavioral sample
M_a3
HDI_a3 <- HPDI( inv_logit( post_cs$d[,3]  ) ) #highest posterior density on probability scale, behavioral sample
HDI_a3


#CS2n
M_a4 <- mean( inv_logit( post_cs$d[,4] ) ) #posterior mean on probability scale, behavioral sample
M_a4
HDI_a4 <- HPDI( inv_logit( post_cs$d[,4]  ) ) #highest posterior density on probability scale, behavioral sample
HDI_a4

#find the proportion of the HPDI that is inside the ROPE
rope(inv_logit( post_cs$d[,1] ), range = c(.45, .55))
rope(inv_logit( post_cs$d[,2] ), range = c(.45, .55))
rope(inv_logit( post_cs$d[,3] ), range = c(.45, .55))
rope(inv_logit( post_cs$d[,4] ), range = c(.45, .55))

```

































